export const TEAM_MEMBERS = [
  "Aaron Abarquez",
  "Abrille Arado",
  "Adonis Mayol",
  "Ador Pajarillaga",
  "Aira Mae Ceniza",
  "Alexandro V. Cerdeña",
  "Aljen Cervantes",
  "Alleona Barrientos",
  "Alvin Surigao",
  "Analiza Levantino",
  "Ann Jean Madlos",
  "Axel Von B. Ruiz",
  "Bai-Aminah Benito",
  "Bethanie Rose Huelar",
  "Bright Echezonachukwu",
  "Bryan Lava",
  "Camille Rose Ann Agero",
  "Charmaine Cabahug",
  "Christina Mikaella Fronteras",
  "Clarisse Ann Cruz",
  "Coleen Maglupay",
  "David James Apad",
  "Dennis Njoroge",
  "Gemma Mercado Awat",
  "Hedaya Balindong",
  "Hishi Keana Bulawan",
  "Ihmee Patentes",
  "Irika Braza",
  "Jake Dawang",
  "Jalaiza Macatangay",
  "Jasen Marie Lopez",
  "Jason Nabung",
  "Jasper Jon Glenogo",
  "Jay Fred Bautista",
  "Jefferson Apolinar",
  "Jeramy Culanag",
  "Jessa Bayot",
  "Joan Campos",
  "Joeval Fiel",
  "John Antonio Abarquez",
  "John Paul Cabasac",
  "John Rey Montero",
  "Joland Valencia",
  "Jonah Vasquez",
  "Joseph Oche Ujah",
  "Josh Stephen Arce",
  "Joshua delos Reyes",
  "Keddrick Jewel Viola",
  "Khalid Sadjail",
  "Kris Gienikko Amable",
  "Lenoel Montilla III",
  "Luiggi Diomaboc",
  "Ma Allyssa Jean Ramirez",
  "Ma. Criselda Consulta",
  "Marc Ceazar Pineda",
  "Marie Grace Solo",
  "Marie Martha Santos",
  "Mariel Carbonell",
  "Mark Giovanni Amable",
  "Mark Jason Morales",
  "Mark Joseph Escalante",
  "Mary Grace Bordado",
  "Mary Joyce Paez",
  "Neljhun Elondo",
  "Noel B. Estrevillo Jr.",
  "Phil Anthony Nierves",
  "Philip Joseph Biscocho",
  "Primo Jorge Pador",
  "Raffy Antic",
  "Ram Arthur Yaba",
  "Ramir Kristoffer Reyes",
  "Rashimar Mohamad",
  "Regine Operania",
  "Renalyn Moradas",
  "Rhae Mae Tubo",
  "Romeo Dimiao",
  "Rose Ann Romero",
  "Sean Baring",
  "Sheila May Bernales",
  "Sherhan Sulaiman Jarol",
  "Shierjon Donie Lagsac",
  "Steffie Ann Bawiga",
  "Zyrene Mae Jarlego",
  "Adrian Lansang",
  "Mikhael Jose Galocgoc",
  "Emmanuel Briggs Adepoju",
  "Cynthia Ngozi Ugochukwu",
  "Paschal Chinaemelum Umeh",
  "Justine Abel Bulawan",
  "Fredrick Damian Chukwu",
].sort((a, b) => a.localeCompare(b));

export const US_STATE_CODES = [
  "AL","AK","AZ","AR","CA","CO","CT","DE","FL","GA","HI","ID","IL","IN","IA",
  "KS","KY","LA","ME","MD","MA","MI","MN","MS","MO","MT","NE","NV","NH","NJ",
  "NM","NY","NC","ND","OH","OK","OR","PA","RI","SC","SD","TN","TX","UT","VT",
  "VA","WA","WV","WI","WY","DC","PR",
];

export const PLATFORMS = [
  "SLASH",
  "NEW AUTHORIZE",
  "BREX",
  "TAILOREDPAYNEW",
  "WORKIZPAY",
  "WORKIZ",
  "DIGITAS",
  "TAILOREDPAY",
];

export const ROLE_LABELS: Record<string, string> = {
  operations_manager: "Operations Manager",
  admin_coordinator: "Admin Coordinator",
  team_leader: "Team Leader",
  agent: "Agent",
};
